### ISSUE TITLE
bug: floats use last used hoverhints highlight

### ISSUE THREAD

**Issue by sravioli** [soulis-1256/hoverhints.nvim#8] opened 2023-12-06 21:50 UTC
pre hover:
![image](https://github.com/soulis-1256/hoverhints.nvim/assets/76562615/8395481a-cd31-427c-9d41-91e7ba26cf54)

hover event:
![image](https://github.com/soulis-1256/hoverhints.nvim/assets/76562615/f8be41e7-9387-41f6-b49b-de3081bf15d2)

post hover:
![image](https://github.com/soulis-1256/hoverhints.nvim/assets/76562615/a4d50b7e-5df5-48fd-8f6f-cd7c9fc6a9f1)

![image](https://github.com/soulis-1256/hoverhints.nvim/assets/76562615/8c23b29e-2ecf-489c-ac8b-e84115b2849b)

![image](https://github.com/soulis-1256/hoverhints.nvim/assets/76562615/00b47973-75d4-4cb9-ba5d-b1279906fe97)

**Comment by soulis-1256** [comment] 2023-12-07 14:42
Could you specify your neovim version?

**Comment by sravioli** [comment] 2023-12-07 14:46
sure:

```sh
$ nvim.exe -V1 --version
NVIM v0.10.0-dev-d667e0e
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /DWIN32 /D_WINDOWS /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -wd4003 -wd4715 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src

   file vimrc di sistema: "$VIM\sysinit.vim"
         $VIM di riserva: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by soulis-1256** [comment] 2023-12-07 16:35
Ok, so I tested with the two configs you sent me. The first one doesn't work at all (it's as if the plugin is disabled), at least with only what you sent me. You shouldn't let lazy handle my plugin, my instructions never said you should experiment so much with it. The second one works (not all the time, but still) and doesn't reproduce your issue. Given this, I would assume the issue has something to do with your Neovim version. If you want my plugin to work as intended, you should use Neovim's stable v0.9.2 or v0.9.4 (the ones I'm testing on) and strictly follow my [readme](https://github.com/soulis-1256/hoverhints.nvim/blob/main/README.md) instructions (with the exception of adding mousemoveevent to the init property of lazy, which seems like a good idea and I might add it myself). I'm going to leave this issue open for another day and await for some more comments from your end. After that, if we don't reach any kind of solution, I'm going to close it. However, if you manage to reproduce this with the stable versions I just talked about, you are welcome to recreate this issue and I can get to work. As of now, trying to fix this with an unstable version of Neovim is just not a wise option. Thank you.

**Closed** 2023-12-09 15:10 UTC

**Comment by gbcreation** [comment] 2024-08-31 01:13
Hi!

I meet this issue too. It seems to be related to value `0` passed as first parameter to the `nvim_set_hl()` call at [this line](https://github.com/soulis-1256/eagle.nvim/blob/main/lua/eagle/init.lua#L158).

Nvim documentation for this parameter:

```
      • {ns_id}  Namespace id for this highlight |nvim_create_namespace()|.
                 Use 0 to set a highlight group globally |:highlight|.
                 Highlights from non-global namespaces are not active by
                 default, use |nvim_set_hl_ns()| or |nvim_win_set_hl_ns()| to
                 activate them.
```

As specified, using `0` set the `FloatBorder` highlight group globally. Doing so overrides the existing `FloatBorder` highlight group and impacts other plugins using this global group.

Could you use a non-global group for Eagle, or just use the existing global group without overriding it?

**Comment by soulis-1256** [comment] 2024-08-31 01:30
@gbcreation Hi, I don't have enough time to look into this right now, but if you think changing this value fixes this issue without causing other problems I could add this as a config option.
